### PR TITLE
Fix admin_level for Bolivia

### PR DESCRIPTION
**Pull request by severo**
Based on https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#11_admin_level_values_for_specific_countries

(See also https://github.com/osm-without-borders/cosmogony-data-dashboard/pull/5#pullrequestreview-145565886)

### CODE REVIEW

**Comment by nlehuby** [comment]
Here are the results with this config:

- "State": 2 element(s)
- "StateDistrict": 98 element(s)
- "City": 315 element(s)
- "CityDistrict": 100 element(s)
- "Suburb": 327 element(s)

From:

- Admin level 4: 2 element(s)
- Admin level 6: 98 element(s)
- Admin level 8: 315 element(s)
- Admin level 9: 88 element(s)
- Admin level 10: 12 element(s)
- Admin level 11: 327 element(s)

**Comment by severo** [comment]
Ideally, following the rules from the OSM wiki, the correct numbers should be:

"State": 9 element(s)
"StateDistrict": 112 element(s)
"City": 339 element(s)

I think it's better to show the problems, to help the Bolivian community to fix the metadata in OSM.

**Review by nlehuby — APPROVED** [review]

**Comment by severo** [comment]
cc @51114u9 @rafemoro @NoemiNahomy

**Comment by nlehuby** [comment]
Yes, I agree :+1: 

Thanks for your contribution!

**Pull request merged**
